### ISSUE TITLE
Android conferencing

### ISSUE THREAD

**Issue by Sreyams** [mesibo/conferencing#10]
I have compiled the Android code and when I execute it, how and where I can do a conference call? I see I can create the room, enter a room but not sure how to make a call.  Please help. In the debug mode, where do I see the audio call initiation etc.?

Is the github code same as the livedemo? because I do not see the same features.

**Comment by heisenberg-hash** [comment]
First, create a room. This room will now have a room-id and pin. You need to share the room-id and pin with people who you want to join the conference. 

Click on the invite participant button to copy the room-id and pin.
![conf-controls](https://user-images.githubusercontent.com/80388244/112265164-06af4700-8c98-11eb-8f99-b5c29880ef23.jpg)

Participants will now be able to enter your room by entering this room-id and pin.

Refer to the  [Conferencing API Documentation](https://mesibo.com/documentation/api/conferencing/) to learn about group call initiation, publishing, and subscribing streams, etc.

**Comment by Sreyams** [comment]
Yes, I have done that way you have suggested. But the question I have is, based on the github code I have compiled, I do not see where one of the participants in the meeting room to make a group call. Is that group call code built into it? I see in the code there is a groupcall section.

I am bit confused here

**Comment by Sreyams** [comment]
I am not sure about which is the UI button to invoke a group call?

**Comment by mesibo** [comment]
Refer to the API documentation to learn how code works 

https://mesibo.com/documentation/api/conferencing

Start with basic demo https://github.com/mesibo/conferencing/tree/master/web/basic-demo
