### ISSUE TITLE
Conferencing cloud server user is different from base server / chat server

### ISSUE THREAD

**Issue by om-ha** [mesibo/conferencing#13]
Hey Mesibo team!

In the cloud API, it seems that conferencing server uses a different database instance! This is apparent since we have to sign-in separately using OTP and the conferencing user doesn't show up in Mesibo dashboard.

For comparison:

- `BaseURL` of Mesibo Base Server & Mesibo API Server: https://api.mesibo.com/api.php
- `BaseURL` of Mesibo Conferencing server: https://app.mesibo.com/conf/api.php ([**SOURCE**](https://github.com/mesibo/conferencing/blob/master/backend/README.md#backend-for-sample-conferencing-app))

My questions:

1. It's fine if cloud API's are like that, but for **on-premise**, can I share the same database instance with the same schema between all 3 servers? base server, chat server, & conferencing server.

2. I think it's possible to turn off OTP for conferencing sign-in by modifying relevant PHP code. And actually skip sign-in altogether from end-users since sign-in (token generation) is done by mesibo backend rest API, and UserId/Token are created anyways using base server. Is my assumption correct?

**Comment by om-ha** [comment]
Nevermind, the database is actually shared between the three servers (base, chat, conferencing)

Even for conferencing server [APIs ](https://github.com/mesibo/conferencing/tree/master/backend#using-private-backend-apis-for-conferencing)(login, setgroup, joingroup), it's possible to use `https://api.mesibo.com/api.php` as well.

Thanks!

**Comment by mesibo** [comment]
Let me further clarify

This is mesibo backend API: https://api.mesibo.com/api.php 

This is the private API of conferencing server/demo https://app.mesibo.com/conf/api.php It internally uses mesibo backend APIs.

**Comment by om-ha** [comment]
Thank you for the clarification.

Is it possible to use the same user token for both APIs? (shared database)

**Comment by om-ha** [comment]
Because so it seems, even though conferencing server internally uses mesibo backend, it has its own user token that needs OTP code (mandatory/required), and looks like it's a different token from mesibo backend APIs.

And to circumvent OTP, it seems like we need on-premise hosting of conferencing server and modify conferencing server API by editing its PHP code to remove OTP functionality.
