### ISSUE TITLE
Save Group Profile will remove Group Setting

### ISSUE THREAD

**Issue by adisiji** [mesibo/conferencing#16]
Hi,
Glad to know that you have been released the new library to setup the Call resolution.
The problem is, I have created a group, but if I set the group `imageUrl` and save it, it will remove the group setting that has been setup when I create the group.

So, I create a group with this method
```
val groupSettings = MesiboGroupProfile.GroupSettings().apply {
            name = groupName
            videoResolution = Mesibo.RESOLUTION_VGA.toLong()
            callFlags = 16777215L
     }
Mesibo.createGroup(groupSettings, listener)
```
After group has successfully created, I set the group image, and add members
```
val mesiboGroupProfile = createSuspendGroup(groupName)
if (groupIcon != Uri.EMPTY) {
  // Here, I set the imageUrl if user is set a picture
  setGroupPicture(this, mesiboGroupProfile )
  // And then save the mesiboGroupProfile 
  mesiboGroupProfile.save()
}

// Add members to group
val membersId = _chosenContacts.value?.map { it.id }?.drop(1)
if (!membersId.isNullOrEmpty()) {
   val members = membersId.toTypedArray()
   val permission = MesiboGroupProfile.MemberPermissions().apply {
         videoResolution = Mesibo.RESOLUTION_VGA.toLong()
         callFlags = 16777215L
   }
   mesiboGroupProfile.addMembers(members, permission)
}
```

To verify my result, I check on the mesibo console.
Here is the result if I invoke `save` profile. The resolution is back to default.
![default quality](https://cdn.discordapp.com/attachments/824541017335660567/889763669574029312/Capture1.PNG)

And then if I don't set imageUrl and `save` doesn't invoked. The resolution is successfullyt set to VGA.
![VGA quality](https://cdn.discordapp.com/attachments/824541017335660567/889763672338079794/Capture2.PNG)

My Android mesibo version:
```
const val MESIBO_CALLS = "1.7.0"
const val MESIBO_API = "1.7.2"
const val MESIBO_UI = "1.7.0"
```

Thank You

**Comment by mesibo** [comment]
Profile save() should not impact call flags and resolution. 

Please try the following:
1) Do not use call flags in the old way, there are defined for Callflags. Else set it to zero(0)
2) Use profile.getGroupProfile().getSettings(listner).  It will give you Permissions for that particular member.  You can check video resolution there, before and after saving profiles. 

If the issue persists, let us know and we will look into it.

**Comment by mesibo** [comment]
Possibly a minor bug in the new video resolution API but we will still appreciate you testing above and share results.

**Comment by adisiji** [comment]
Yeah. It worked now. 
I don't change any code. But when I checked again, it all worked on mesibo console.
Thanks!

**Comment by mesibo** [comment]
We have discovered a tiny bug, thanks to your report. Currently, it is masked in the console and hence you won't face it. However, we are soon releasing an API update and new conferencing code for Android, iOS, and Web which uses new APIs. Please update once it is released
