### ISSUE TITLE
android kotlin code for conferencing

### ISSUE THREAD

**Issue by AparnaManjalavil** [mesibo/conferencing#4]
I have to implement Group calling or Conference call in Android app. Is there any source code available for implementing this feature in Android kotlin

**Comment by om-ha** [comment]
I am also wondering if video conferencing is supported

One-Video-Streamer to Many-Subscribers

Platforms: iOS/Android/Web

**Comment by mesibo** [comment]
Please refer to the documentation https://mesibo.com/documentation/conferencing/
