### ISSUE TITLE
conference demo not working

### ISSUE THREAD

**Issue by lordmen99** [mesibo/conferencing#5]
only stuck after create room when try demo conference

**Comment by mesibo** [comment]
You have not given sufficient details for us to look into the issue. 

However, the same code running here. Please check if you are facing the same issue https://mesibo.com/livedemo/

**Comment by lordmen99** [comment]
issue from here 
 https://mesibo.com/livedemo/

**Comment by mesibo** [comment]
You have not given sufficient details for us to look into the issue.

Closed.

**Comment by lordmen99** [comment]
try ur self. its stuck dude after create room

**Comment by mesibo** [comment]
It's working for me. There might be a possible connection issue at your end, please try a hard refresh. If you still having issues after hard refresh, post the logs from the console and we will look into it ASAP.

**Comment by lordmen99** [comment]
working now,and for demo messenger android cant login, otp not send

**Comment by mesibo** [comment]
Glad it worked for you. 

Currently, we send OTP to a few countries only - refer https://mesibo.com/documentation/faq/demo-apps/#i-am-not-receiving-the-otp-what-do-i-do 

You can also contact us  https://mesibo.com/help
