### ISSUE TITLE
mesibo

### ISSUE THREAD

**Issue by Sreyams** [mesibo/conferencing#9]

**Comment by Sreyams** [comment]
Hi,

I am trying to evaluate mesibo conferencing features. I have downloaded and compiled the code successfully on Android. I have created the app, users and groups under the app names com.mesibo.confdemo. When I run the app on Android, giving the name as Sreyams, email as sreyams.jain@stefanini.com, I get the Enter OTP code sent to sreyams.jain@stefanini.com . However, I do not get this email at all. In fact, I have requested support@mesibo.com to get me this OTP as well. No one has responded.

Can some one look into this and reply, please.

**Comment by mesibo** [comment]
We have responded to your ticket. Possibly you didn't get that too and hence there is an issue with your email.

Use other email addresses, for example, Gmail to test the demo.

**Comment by Sreyams** [comment]
Thanks, it works with a gmail id. 

Are the rooms created within the app, does it show up in my mesibo console? Is there a way to delete the rooms created as well?
